// Model catalogue covering two distinct classes:
//   type 'embedding'  — text in, vector out. Billed on input tokens only.
//   type 'generation' — text in, text out. Billed on input AND output tokens.
// Prices are provider list prices in USD per 1M tokens and change over time —
// verify against provider pricing pages before relying on them.
// `exactTokenizer` marks models that genuinely use cl100k_base; others are approximated.
const models = {
  'openai-3-small': {
    name: 'text-embedding-3-small',
    provider: 'OpenAI',
    type: 'embedding',
    dimensions: 1536,
    pricePerMillionTokens: 0.02,
    maxTokens: 8191,
    tokenizer: 'cl100k_base',
    exactTokenizer: true,
  },
  'openai-3-large': {
    name: 'text-embedding-3-large',
    provider: 'OpenAI',
    type: 'embedding',
    dimensions: 3072,
    pricePerMillionTokens: 0.13,
    maxTokens: 8191,
    tokenizer: 'cl100k_base',
    exactTokenizer: true,
  },
  'openai-ada-002': {
    name: 'text-embedding-ada-002 (legacy)',
    provider: 'OpenAI',
    type: 'embedding',
    dimensions: 1536,
    pricePerMillionTokens: 0.1,
    maxTokens: 8191,
    tokenizer: 'cl100k_base',
    exactTokenizer: true,
  },
  'azure-3-small': {
    name: 'text-embedding-3-small',
    provider: 'Azure OpenAI',
    type: 'embedding',
    dimensions: 1536,
    pricePerMillionTokens: 0.02,
    maxTokens: 8191,
    tokenizer: 'cl100k_base',
    exactTokenizer: true,
    note: 'Same model as OpenAI, hosted in your Azure tenant. Regional pricing may differ.',
  },
  'azure-3-large': {
    name: 'text-embedding-3-large',
    provider: 'Azure OpenAI',
    type: 'embedding',
    dimensions: 3072,
    pricePerMillionTokens: 0.13,
    maxTokens: 8191,
    tokenizer: 'cl100k_base',
    exactTokenizer: true,
    note: 'Same model as OpenAI, hosted in your Azure tenant. Regional pricing may differ.',
  },
  'cohere-v3': {
    name: 'Embed English v3.0',
    provider: 'Cohere',
    type: 'embedding',
    dimensions: 1024,
    pricePerMillionTokens: 0.1,
    maxTokens: 512,
    tokenizer: 'Cohere BPE (approximated)',
    exactTokenizer: false,
  },  'voyage-3': {
    name: 'voyage-3',
    provider: 'Voyage AI',
    type: 'embedding',
    dimensions: 1024,
    pricePerMillionTokens: 0.06,
    maxTokens: 32000,
    tokenizer: 'Voyage BPE (approximated)',
    exactTokenizer: false,
  },
  'google-text-004': {
    name: 'text-embedding-004',
    provider: 'Google',
    type: 'embedding',
    dimensions: 768,
    pricePerMillionTokens: 0.025,
    maxTokens: 2048,
    tokenizer: 'SentencePiece (approximated)',
    exactTokenizer: false,
  },

  // --- Generation models: billed on input AND output tokens ---
  'gpt-4o': {
    name: 'GPT-4o',
    provider: 'OpenAI',
    type: 'generation',
    cacheReadMultiplier: 0.5,
    pricePerMillionTokens: 2.5,
    outputPricePerMillionTokens: 10,
    maxTokens: 128000,
    tokenizer: 'o200k_base (approximated with cl100k_base)',
    exactTokenizer: false,
    note: 'Generation model — billed on input and output tokens.',
  },
  'gpt-4o-mini': {
    name: 'GPT-4o mini',
    provider: 'OpenAI',
    type: 'generation',
    cacheReadMultiplier: 0.5,
    pricePerMillionTokens: 0.15,
    outputPricePerMillionTokens: 0.6,
    maxTokens: 128000,
    tokenizer: 'o200k_base (approximated with cl100k_base)',
    exactTokenizer: false,
    note: 'Generation model — billed on input and output tokens.',
  },
  'azure-gpt-4o': {
    name: 'GPT-4o',
    provider: 'Azure OpenAI',
    type: 'generation',
    cacheReadMultiplier: 0.5,
    pricePerMillionTokens: 2.5,
    outputPricePerMillionTokens: 10,
    maxTokens: 128000,
    tokenizer: 'o200k_base (approximated with cl100k_base)',
    exactTokenizer: false,
    note: 'Same model as OpenAI, hosted in your Azure tenant. Regional pricing may differ.',
  },
  'azure-gpt-4o-mini': {
    name: 'GPT-4o mini',
    provider: 'Azure OpenAI',
    type: 'generation',
    cacheReadMultiplier: 0.5,
    pricePerMillionTokens: 0.15,
    outputPricePerMillionTokens: 0.6,
    maxTokens: 128000,
    tokenizer: 'o200k_base (approximated with cl100k_base)',
    exactTokenizer: false,
    note: 'Same model as OpenAI, hosted in your Azure tenant. Regional pricing may differ.',
  },
  'claude-opus-4': {
    name: 'Claude Opus 4.1',
    provider: 'Anthropic',
    type: 'generation',
    cacheReadMultiplier: 0.1,
    pricePerMillionTokens: 15,
    outputPricePerMillionTokens: 75,
    maxTokens: 200000,
    tokenizer: 'Anthropic BPE (approximated)',
    exactTokenizer: false,
    note: 'Generation model — billed on input and output tokens. Anthropic does not offer an embedding model.',
  },
  'claude-sonnet-4': {
    name: 'Claude Sonnet 4.5',
    provider: 'Anthropic',
    type: 'generation',
    cacheReadMultiplier: 0.1,
    pricePerMillionTokens: 3,
    outputPricePerMillionTokens: 15,
    maxTokens: 200000,
    tokenizer: 'Anthropic BPE (approximated)',
    exactTokenizer: false,
    note: 'Generation model — billed on input and output tokens. Anthropic does not offer an embedding model.',
  },
  'claude-haiku-4': {
    name: 'Claude Haiku 4.5',
    provider: 'Anthropic',
    type: 'generation',
    cacheReadMultiplier: 0.1,
    pricePerMillionTokens: 1,
    outputPricePerMillionTokens: 5,
    maxTokens: 200000,
    tokenizer: 'Anthropic BPE (approximated)',
    exactTokenizer: false,
    note: 'Generation model — billed on input and output tokens. Anthropic does not offer an embedding model.',
  },
  'gemini-flash': {
    name: 'Gemini 2.0 Flash',
    provider: 'Google',
    type: 'generation',
    cacheReadMultiplier: 0.25,
    pricePerMillionTokens: 0.1,
    outputPricePerMillionTokens: 0.4,
    maxTokens: 1000000,
    tokenizer: 'SentencePiece (approximated)',
    exactTokenizer: false,
    note: 'Generation model — billed on input and output tokens.',
  },
  'gemini-pro': {
    name: 'Gemini 2.5 Pro',
    provider: 'Google',
    type: 'generation',
    cacheReadMultiplier: 0.25,
    pricePerMillionTokens: 1.25,
    outputPricePerMillionTokens: 10,
    maxTokens: 1000000,
    tokenizer: 'SentencePiece (approximated)',
    exactTokenizer: false,
    note: 'Generation model — billed on input and output tokens.',
  },
};

module.exports = models;
